=== kdk-pkg-soft/freehep-ncolor-pdf/site/src/site/resources/freehep1.x/schemas/heprep/1.0/HepRep.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- $Id: HepRep.xsd 8986 2006-09-15 23:39:54Z duns $ -->
<!-- Document Type Definition for the HEPREP Descriptions -->

<xs:schema targetNamespace="http://java.freehep.org/schemas/heprep/1.0" xmlns="http://java.freehep.org/schemas/heprep/1.0"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:annotation>
    <xs:documentation source="http://heprep.freehep.org/">HepRep Version 1 XML Format</xs:documentation>
  </xs:annotation>

  <xs:complexType name="attdef">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="desc" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="extra" type="xs:string" />
  </xs:complexType>
  <xs:element name="attdef" type="attdef" />

  <xs:complexType name="attvalue">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="value" type="xs:string" />
    <xs:attribute name="showLabel" type="xs:int" default="0" />
  </xs:complexType>
  <xs:element name="attvalue" type="attvalue" />

  <xs:complexType name="point">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attdef" />
      <xs:element ref="attvalue" />
    </xs:choice>
    <xs:attribute name="x" type="xs:double" />
    <xs:attribute name="y" type="xs:double" />
    <xs:attribute name="z" type="xs:double" />
  </xs:complexType>
  <xs:element name="point" type="point" />

  <xs:complexType name="primitive">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attdef" />
      <xs:element ref="attvalue" />
      <xs:element ref="point" />
    </xs:choice>
  </xs:complexType>
  <xs:element name="primitive" type="primitive" />

  <xs:complexType name="instance">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attdef" />
      <xs:element ref="attvalue" />
      <xs:element ref="type" />
      <xs:element ref="primitive" />
      <xs:element ref="point" />
    </xs:choice>
  </xs:complexType>
  <xs:element name="instance" type="instance" />

  <xs:complexType name="type">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attdef" />
      <xs:element ref="attvalue" />
      <xs:element ref="instance" />
      <xs:element ref="type" />
      <xs:element ref="primitive" />
      <xs:element ref="point" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="version" type="xs:string" />
  </xs:complexType>
  <xs:element name="type" type="type" />

  <xs:element name="heprep">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="attdef" />
        <xs:element ref="attvalue" />
        <xs:element ref="type" />
      </xs:choice>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/Ellipse.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestEllipse">
        <heprep:attvalue name="drawAs" value="Ellipse" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:attvalue name="drawAs" value="Point" />
                <heprep:point x="0.0" y="0.0" z="0.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="lineColor" value="cyan" />
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="2.0" y="0.0" z="0.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="lineColor" value="orange" />
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="0.0" y="2.0" z="0.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="lineColor" value="green" />
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="0.0" y="0.0" z="2.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="2.0" y="2.0" z="2.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="Sum" value="7"/>
                <heprep:point x="10.0" y="10.0" z="10.0" />
                <heprep:point x="14.0" y="12.0" z="11.0" />
            </heprep:primitive>            
            <heprep:primitive>
                <heprep:attvalue name="Sum" value="10"/>
                <heprep:attvalue name="Phi" value="2.3"/>
                <heprep:point x="-10.0" y="10.0" z="10.0" />
                <heprep:point x="-12.0" y="9.0"  z="11.0" />
            </heprep:primitive>            
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/Template.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestObject">
        <heprep:attvalue name="drawAs" value="" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:point x="0.0" y="0.0" z="0.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="" value=""/>
                <heprep:point x="10.0" y="10.0" z="10.0" />
            </heprep:primitive>            
            <heprep:primitive>
                <heprep:attvalue name="" value=""/>
                <heprep:point x="-10.0" y="10.0" z="10.0" />
            </heprep:primitive>            
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>
