=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep/src/main/resources/hep/graphics/heprep/xml/HepRep.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- $Id: HepRep.xsd 8617 2006-08-16 07:39:12Z duns $ -->
<!-- Document Type Definition for the HEPREP Descriptions -->

<xs:schema version="2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://java.freehep.org/schemas/heprep/2.0"
  targetNamespace="http://java.freehep.org/schemas/heprep/2.0">

  <xs:annotation>
    <xs:documentation source="http://heprep.freehep.org/">
      HepRep Version 2 XML Format
    </xs:documentation>
  </xs:annotation>

  <xs:complexType name="attvalue">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="value" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="showlabel" type="xs:string" default="NAME" />
  </xs:complexType>
  <xs:element name="attvalue" type="attvalue"/>

  <xs:complexType name="attdef">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="desc" type="xs:string" />
    <xs:attribute name="category" type="xs:string" />
    <xs:attribute name="extra" type="xs:string" />
  </xs:complexType>
  <xs:element name="attdef" type="attdef"/>

  <xs:complexType name="point">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attvalue"/>
    </xs:choice>
    <xs:attribute name="x" type="xs:double" />
    <xs:attribute name="y" type="xs:double" />
    <xs:attribute name="z" type="xs:double" />
  </xs:complexType>
  <xs:element name="point" type="point"/>

  <xs:complexType name="action">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="expression" type="xs:string" />
  </xs:complexType>
  <xs:element name="action" type="action"/>

  <xs:complexType name="type">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attvalue" />
      <xs:element ref="attdef" />
      <xs:element ref="type" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
  <xs:element name="type" type="type"/>

  <xs:complexType name="instance">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attvalue" />
      <xs:element ref="point" />
      <xs:element ref="instance" />
    </xs:choice>
    <xs:attribute name="type" type="xs:string" />
  </xs:complexType>
  <xs:element name="instance" type="instance"/>

  <xs:complexType name="treeid">
    <xs:attribute name="qualifier" type="xs:string" />
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="version" type="xs:string" />
  </xs:complexType>
  <xs:element name="treeid" type="treeid"/>

  <xs:complexType name="instancetree">
    <xs:complexContent>
      <xs:extension base="treeid">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="treeid" />
          <xs:element ref="instance" />
        </xs:choice>
        <xs:attribute name="typetreename" type="xs:string" />
        <xs:attribute name="typetreeversion" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="instancetree" type="instancetree"/>

  <xs:complexType name="typetree">
    <xs:complexContent>
      <xs:extension base="treeid">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="type" />
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="typetree" type="typetree"/>

  <xs:complexType name="layer">
    <xs:attribute name="order" type="xs:string" />
  </xs:complexType>
  <xs:element name="layer" type="layer"/>

  <xs:element name="heprep">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="layer" />
        <xs:element ref="typetree" />
        <xs:element ref="instancetree" />
      </xs:choice>
      <xs:attribute name="version" type="xs:string" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/PolyEllipse.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestPolyEllipse">
        <heprep:attvalue name="drawAs" value="PolyEllipse" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="2.0" y="2.0" z="2.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="Sum" value="7"/>
                <heprep:point x="10.0" y="10.0" z="10.0" />
                <heprep:point x="14.0" y="12.0" z="11.0" />
                <heprep:point x="20.0" y="20.0" z="20.0" />
                <heprep:point x="24.0" y="22.0" z="21.0" />
            </heprep:primitive>            
            <heprep:primitive>
                <heprep:attvalue name="Sum" value="10"/>
                <heprep:attvalue name="Phi" value="2.3"/>
                <heprep:point x="-10.0" y="10.0" z="10.0" />
                <heprep:point x="-12.0" y="9.0"  z="11.0" />
                <heprep:point x="-20.0" y="10.0" z="20.0" />
                <heprep:point x="-22.0" y="19.0" z="21.0" />
                <heprep:point x="-30.0" y="30.0" z="30.0" />
                <heprep:point x="-32.0" y="39.0" z="31.0" />
            </heprep:primitive>            
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/Text.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestText">
        <heprep:attvalue name="drawAs" value="Text" />
        <heprep:attvalue name="HPos" value="0.7" />
        <heprep:attvalue name="VPos" value="0.3" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:point x="0.0" y="0.0" z="0.0" />
            </heprep:primitive>
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-cheprep/src/ref/HepRepTest.xml
<?xml version="1.0" ?>
<heprep version="2.0"
  xmlns="http://java.freehep.org/schemas/heprep/2.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://java.freehep.org/schemas/heprep/2.0 http://java.freehep.org/schemas/heprep/2.0/HepRep.xsd">
  <layer order="Detector"/>
  <typetree name="CylinderType" version="1.0">
    <type name="Cylinder">
      <attvalue name="banner" type="boolean" value="true"/>
      <attvalue name="framed" type="boolean" value="true"/>
      <attvalue name="drawAs" value="Cylinder"/>
      <attvalue name="radius1" type="double" value="2"/>
      <attvalue name="radius2" showlabel="NAME, VALUE, 400"
        type="double" value="2"/>
    </type>
  </typetree>
  <instancetree name="TestCylinder"
    typetreename="CylinderType" typetreeversion="1.0" version="CPlusPlus Generated">
    <instance type="Cylinder">
      <attvalue name="color" type="Color"
        value="1.00, 0.00, 0.00, 1.00"/>
      <attvalue name="label" showlabel="VALUE" value="x-axis"/>
      <point x="0" y="0" z="0"/>
      <point x="4" y="0" z="0"/>
    </instance>
    <instance type="Cylinder">
      <attvalue name="color" type="Color"
        value="0.00, 1.00, 0.00, 1.00"/>
      <attvalue name="label" showlabel="VALUE" value="y-axis"/>
      <point x="0" y="0" z="0"/>
      <point x="0" y="4" z="0"/>
    </instance>
    <instance type="Cylinder">
      <attvalue name="color" type="Color"
        value="0.00, 1.00, 0.00, 1.00"/>
      <attvalue name="label" showlabel="VALUE" value="z-axis"/>
      <point x="0" y="0" z="0"/>
      <point x="0" y="0" z="4"/>
    </instance>
    <instance type="Cylinder">
      <attvalue name="Phi1" type="double" value="0.2"/>
      <attvalue name="Phi2" type="double" value="0.3"/>
      <point x="3.4e-006" y="10" z="1.20003e+006"/>
      <point x="12.3" y="12.3" z="12.3"/>
    </instance>
  </instancetree>
</heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/resources/hep/graphics/heprep1/xml/AttributeDefaults.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:attvalue name="DrawAs"              value="PolyPoint" />
    <heprep:attvalue name="DrawAsOptions"       value="PolyPoint" />

<!-- to be placed correctly ... -->
    <heprep:attvalue name="Label"               value="" />
    <heprep:attvalue name="Visibility"          value="True" />

<!-- TextAtts -->
    <heprep:attvalue name="FontName"            value="SansSerif" />
    <heprep:attvalue name="FontStyle"           value="Plain" />
    <heprep:attvalue name="FontSize"            value="12" />
    <heprep:attvalue name="FontColor"           value="White" />
    <heprep:attvalue name="FontHasFrame"        value="True" />
    <heprep:attvalue name="FontFrameColor"      value="Black" />
    <heprep:attvalue name="FontFrameWidth"      value="2" />
    <heprep:attvalue name="FontHasBanner"       value="False" />
    <heprep:attvalue name="FontBannerColor"     value="Black" />

<!-- SinglePointAtts -->
    <heprep:attvalue name="Layer"               value="100" />
    <heprep:attvalue name="MarkName"            value="Dot" />
    <heprep:attvalue name="MarkSize"            value="6" />
    <heprep:attvalue name="MarkColor"           value="White" />
    <heprep:attvalue name="MarkHasFrame"        value="True" />
    <heprep:attvalue name="MarkFrameColor"      value="Black" />
    <heprep:attvalue name="MarkFrameWidth"      value="2" />

<!-- MultiPointsAtts -->
    <heprep:attvalue name="LineColor"           value="White" />
    <heprep:attvalue name="LineStyle"           value="Solid" />
    <heprep:attvalue name="LineWidth"           value="2" />
    <heprep:attvalue name="LineHasFrame"        value="True" />
    <heprep:attvalue name="LineFrameColor"      value="Black" />
    <heprep:attvalue name="LineFrameWidth"      value="2" />

<!-- FillAtts -->
    <heprep:attvalue name="FillColor"           value="White" />
    <heprep:attvalue name="Fill"                value="False" />
    
<!-- SpecificAtts -->
    <heprep:attvalue name="Radius"              value="6" />
    <heprep:attvalue name="Phi"                 value="0" />
    <heprep:attvalue name="Theta"               value="0" />
    <heprep:attvalue name="Omega"               value="0" />
    <heprep:attvalue name="Radius1"             value="5" />
    <heprep:attvalue name="Phi1"                value="0" />
    <heprep:attvalue name="Theta1"              value="0" />
    <heprep:attvalue name="Radius2"             value="5" />
    <heprep:attvalue name="Phi2"                value="0" />
    <heprep:attvalue name="Theta2"              value="0" />
    <heprep:attvalue name="Sum"                 value="5" />
    <heprep:attvalue name="Sum1"                value="5" />
    <heprep:attvalue name="Sum2"                value="5" />
    <heprep:attvalue name="RadiusX"             value="5" />
    <heprep:attvalue name="RadiusY"             value="5" />
    <heprep:attvalue name="RadiusZ"             value="5" />
    <heprep:attvalue name="Curvature"           value="0.02" />
    <heprep:attvalue name="FlyLength"           value="10" />

<!-- 2D TextAtts -->
    <heprep:attvalue name="Text"                value="" />
    <heprep:attvalue name="HPos"                value="1.0" />
    <heprep:attvalue name="VPos"                value="0.5" />
    <heprep:attvalue name="HAlign"              value="Center" />
    <heprep:attvalue name="VAlign"              value="Bottom" />

</heprep:heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/Cylinder.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestCylinder">
        <heprep:attvalue name="banner" value="true" />
        <heprep:attvalue name="framed" value="true" />
        <heprep:attvalue name="drawAs" value="Cylinder" />
        <heprep:attvalue name="radius1" value="2" />
        <heprep:attvalue name="radius2" value="2" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:attvalue name="lineColor" value="cyan" />
                <heprep:attvalue name="label" value="x-axis" showLabel="1" />
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="4.0" y="0.0" z="0.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="lineColor" value="orange" />
                <heprep:attvalue name="label" value="y-axis" showLabel="1" />
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="0.0" y="4.0" z="0.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="lineColor" value="green" />
                <heprep:attvalue name="label" value="z-axis" showLabel="1" />
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="0.0" y="0.0" z="4.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="Phi1" value="0.2" showLabel="1" />
                <heprep:attvalue name="Phi2" value="0.3" showLabel="1" />
                <heprep:point x="10.0" y="10.0" z="10.0" />
                <heprep:point x="12.3" y="12.3" z="12.3" />
            </heprep:primitive>            
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/PolyLine.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestPolyLine">
        <heprep:attvalue name="drawAs" value="PolyLine" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="1.0" y="5.0" z="2.0" />
                <heprep:point x="2.0" y="3.0" z="4.0" />
                <heprep:point x="3.0" y="1.0" z="2.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="LineWidth" value="4"/>
                <heprep:point x="10.0" y="10.0" z="10.0" />
                <heprep:point x="11.0" y="15.0" z="12.0" />
                <heprep:point x="12.0" y="13.0" z="14.0" />
                <heprep:point x="13.0" y="11.0" z="12.0" />
            </heprep:primitive>            
            <heprep:primitive>
                <heprep:attvalue name="LineStyle" value="Dashed"/>
                <heprep:point x="-10.0" y="10.0" z="10.0" />
                <heprep:point x="-11.0" y="15.0" z="12.0" />
                <heprep:point x="-12.0" y="13.0" z="14.0" />
                <heprep:point x="-13.0" y="11.0" z="12.0" />
            </heprep:primitive>            
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/SampleEvent.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- DOCTYPE heprep SYSTEM "HepRep.dtd" -->
<!-- $Id: SampleEvent.xml 8617 2006-08-16 07:39:12Z duns $ -->

<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:attdef name="drawAs" desc="representation" type="Draw"/>
    
    <heprep:type name="Track">
        <heprep:instance>
            <heprep:attvalue name="no" value="5"/>
            <heprep:primitive>
                <heprep:attvalue name="drawAs" value="HelixSegment"/>
                <heprep:point x="0.0" y="0.0" z="0.0">
                </heprep:point>
            </heprep:primitive>
        </heprep:instance>

        <heprep:type name="HitOnTrack">
            <heprep:instance>
                <heprep:attvalue name="no" value="6"/>
                <heprep:primitive>
                    <heprep:attvalue name="drawAs" value="HyperCircle"/>
                    <heprep:point x="0.0" y="0.0" z="0.0">
                    </heprep:point>
                </heprep:primitive>
            </heprep:instance>
        </heprep:type>

        <heprep:type name="KalManPoint">
            <heprep:instance>
                <heprep:attvalue name="no" value="9"/>
                <heprep:primitive>
                    <heprep:attvalue name="drawAs" value="HelixSegment"/>
                    <heprep:point x="0.0" y="0.0" z="0.0">
                    </heprep:point>
                </heprep:primitive> 
            </heprep:instance>
        </heprep:type>
    </heprep:type>

    <heprep:type name="Cluster">
        <heprep:instance>
            <heprep:attvalue name="no" value="12"/>
            <heprep:primitive>
                <heprep:attvalue name="drawAs" value="Box"/>
                <heprep:point x="0.0" y="0.0" z="0.0">
                </heprep:point>
                <heprep:point x="0.0" y="0.0" z="0.0">
                </heprep:point>            
                <heprep:point x="0.0" y="0.0" z="0.0"> 
                </heprep:point>            
            </heprep:primitive>
        </heprep:instance>
    </heprep:type>
    
    <heprep:type name="HitStrip">
        <heprep:instance>
            <heprep:attvalue name="no" value="324"/>
            <heprep:primitive>
                <heprep:attvalue name="drawAs" value="PolyLine"/>
                <heprep:point x="0.0" y="0.0" z="0.0"> 
                </heprep:point>
                <heprep:point x="0.0" y="0.0" z="0.0">
                </heprep:point>                        
            </heprep:primitive>
        </heprep:instance>        
    </heprep:type>
    
</heprep:heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/Point.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestPoint">
        <heprep:attvalue name="drawAs" value="Point" />
        <heprep:attvalue name="MarkFrame" value="True" />
        <heprep:attvalue name="MarkName" value="Square" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:point x="0.0" y="0.0" z="0.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="MarkColor" value="blue"/>
                <heprep:attvalue name="MarkFrameColor" value="white"/>
                <heprep:point x="10.0" y="10.0" z="10.0" />
            </heprep:primitive>            
            <heprep:primitive>
                <heprep:attvalue name="MarkSize" value="10"/>
                <heprep:point x="-10.0" y="10.0" z="10.0" />
            </heprep:primitive>            
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>
