=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep/src/main/resources/hep/graphics/heprep/xml/HepRep.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- $Id: HepRep.xsd 8617 2006-08-16 07:39:12Z duns $ -->
<!-- Document Type Definition for the HEPREP Descriptions -->

<xs:schema version="2.0" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://java.freehep.org/schemas/heprep/2.0"
  targetNamespace="http://java.freehep.org/schemas/heprep/2.0">

  <xs:annotation>
    <xs:documentation source="http://heprep.freehep.org/">
      HepRep Version 2 XML Format
    </xs:documentation>
  </xs:annotation>

  <xs:complexType name="attvalue">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="value" type="xs:string" />
    <xs:attribute name="type" type="xs:string" />
    <xs:attribute name="showlabel" type="xs:string" default="NAME" />
  </xs:complexType>
  <xs:element name="attvalue" type="attvalue"/>

  <xs:complexType name="attdef">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="desc" type="xs:string" />
    <xs:attribute name="category" type="xs:string" />
    <xs:attribute name="extra" type="xs:string" />
  </xs:complexType>
  <xs:element name="attdef" type="attdef"/>

  <xs:complexType name="point">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attvalue"/>
    </xs:choice>
    <xs:attribute name="x" type="xs:double" />
    <xs:attribute name="y" type="xs:double" />
    <xs:attribute name="z" type="xs:double" />
  </xs:complexType>
  <xs:element name="point" type="point"/>

  <xs:complexType name="action">
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="expression" type="xs:string" />
  </xs:complexType>
  <xs:element name="action" type="action"/>

  <xs:complexType name="type">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attvalue" />
      <xs:element ref="attdef" />
      <xs:element ref="type" />
    </xs:choice>
    <xs:attribute name="name" type="xs:string" />
  </xs:complexType>
  <xs:element name="type" type="type"/>

  <xs:complexType name="instance">
    <xs:choice minOccurs="0" maxOccurs="unbounded">
      <xs:element ref="attvalue" />
      <xs:element ref="point" />
      <xs:element ref="instance" />
    </xs:choice>
    <xs:attribute name="type" type="xs:string" />
  </xs:complexType>
  <xs:element name="instance" type="instance"/>

  <xs:complexType name="treeid">
    <xs:attribute name="qualifier" type="xs:string" />
    <xs:attribute name="name" type="xs:string" />
    <xs:attribute name="version" type="xs:string" />
  </xs:complexType>
  <xs:element name="treeid" type="treeid"/>

  <xs:complexType name="instancetree">
    <xs:complexContent>
      <xs:extension base="treeid">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="treeid" />
          <xs:element ref="instance" />
        </xs:choice>
        <xs:attribute name="typetreename" type="xs:string" />
        <xs:attribute name="typetreeversion" type="xs:string" />
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="instancetree" type="instancetree"/>

  <xs:complexType name="typetree">
    <xs:complexContent>
      <xs:extension base="treeid">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
          <xs:element ref="type" />
        </xs:choice>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  <xs:element name="typetree" type="typetree"/>

  <xs:complexType name="layer">
    <xs:attribute name="order" type="xs:string" />
  </xs:complexType>
  <xs:element name="layer" type="layer"/>

  <xs:element name="heprep">
    <xs:complexType>
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="layer" />
        <xs:element ref="typetree" />
        <xs:element ref="instancetree" />
      </xs:choice>
      <xs:attribute name="version" type="xs:string" />
    </xs:complexType>
  </xs:element>

</xs:schema>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep/src/main/resources/hep/graphics/heprep/xml/AttributeDefaults.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep version="2.0"
        xmlns='http://java.freehep.org/schemas/heprep/2.0'
        xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
        xsi:schemaLocation='http://java.freehep.org/schemas/heprep/2.0 http://java.freehep.org/schemas/heprep/2.0/HepRep.xsd'>

    <typetree name="defaults" version="1.0">
        <type name="default">

            <attdef   name="DrawAs"              desc="" category="Draw" extra="" />
            <attvalue name="DrawAs"              value="Point"           type="String" />
            <attdef   name="DrawAsOptions"       desc="" category="Draw" extra="" />
            <attvalue name="DrawAsOptions"       value="Point"           type="String" />
            <attdef   name="Visibility"          desc="" category="Draw" extra="" />
            <attvalue name="Visibility"          value="true"            type="boolean" />

        <!-- to be placed correctly ... -->
            <attdef   name="Label"               desc="" category="Draw" extra="" />
            <attvalue name="Label"               value=""                type="String" />

        <!-- TextAtts -->
            <attdef   name="FontName"            desc="" category="Draw" extra="" />
            <attvalue name="FontName"            value="SansSerif"       type="String" />
            <attdef   name="FontStyle"           desc="" category="Draw" extra="" />
            <attvalue name="FontStyle"           value="Plain"           type="String" />
            <attdef   name="FontSize"            desc="" category="Draw" extra="" />
            <attvalue name="FontSize"            value="12"              type="int"    />
            <attdef   name="FontColor"           desc="" category="Draw" extra="" />
            <attvalue name="FontColor"           value="White"           type="Color"  />
            <attdef   name="FontHasFrame"        desc="" category="Draw" extra="" />
            <attvalue name="FontHasFrame"        value="false"           type="boolean"/>
            <attdef   name="FontFrameColor"      desc="" category="Draw" extra="" />
            <attvalue name="FontFrameColor"      value="White"           type="Color"  />
            <attdef   name="FontFrameWidth"      desc="" category="Draw" extra="" />
            <attvalue name="FontFrameWidth"      value="1"               type="double" />
            <attdef   name="FontHasBanner"       desc="" category="Draw" extra="" />
            <attvalue name="FontHasBanner"       value="false"           type="boolean"/>
            <attdef   name="FontBannerColor"     desc="" category="Draw" extra="" />
            <attvalue name="FontBannerColor"     value="Black"           type="Color"  />

        <!-- SinglePointAtts -->
            <attdef   name="Color"               desc="" category="Draw" extra="" />
            <attvalue name="Color"               value="White"           type="Color"  />
            <attdef   name="Layer"               desc="" category="Draw" extra="" />
            <attvalue name="Layer"               value="default"         type="String" />
            <attdef   name="MarkName"            desc="" category="Draw" extra="" />
            <attvalue name="MarkName"            value="Circle"          type="String" />
            <attdef   name="MarkSize"            desc="" category="Draw" extra="" />
            <attvalue name="MarkSize"            value="5"               type="double" />
            <attdef   name="MarkSizeMultiplier"  desc="" category="Draw" extra="" />
            <attvalue name="MarkSizeMultiplier"  value="1"               type="double" />
            <attdef   name="MarkType"            desc="" category="Draw" extra="" />
            <attvalue name="MarkType"            value="Symbol"          type="String" />
<!-- other value for MarkType is "Real" -->
            <attdef   name="HasFrame"            desc="" category="Draw" extra="" />
            <attvalue name="HasFrame"            value="true"            type="boolean"/>
            <attdef   name="FrameColor"          desc="" category="Draw" extra="" />
            <attvalue name="FrameColor"          value="Black"           type="Color"  />
            <attdef   name="FrameWidth"          desc="" category="Draw" extra="" />
            <attvalue name="FrameWidth"          value="1"               type="double" />

        <!-- MultiPointsAtts -->
            <attdef   name="LineStyle"           desc="" category="Draw" extra="" />
            <attvalue name="LineStyle"           value="Solid"           type="String" />
            <attdef   name="LineWidth"           desc="" category="Draw" extra="" />
            <attvalue name="LineWidth"           value="2"               type="double" />
            <attdef   name="LineWidthMultiplier" desc="" category="Draw" extra="" />
            <attvalue name="LineWidthMultiplier" value="1"               type="double" />
            <attdef   name="LineHasArrow"        desc="" category="Draw" extra="" />
            <attvalue name="LineHasArrow"        value="None"            type="String"/>

        <!-- FillAtts -->
            <attdef   name="FillColor"           desc="" category="Draw" extra="" />
            <attvalue name="FillColor"           value="White"           type="Color"  />
            <attdef   name="FillType"            desc="" category="Draw" extra="" />
            <attvalue name="FillType"            value="EvenOdd"         type="String" />
            <attdef   name="Fill"                desc="" category="Draw" extra="" />
            <attvalue name="Fill"                value="false"           type="boolean"/>

        <!-- SpecificAtts -->
            <attdef   name="Radius"              desc="" category="Draw" extra="" />
            <attvalue name="Radius"              value="5"               type="double" />
            <attdef   name="Phi"                 desc="" category="Draw" extra="" />
            <attvalue name="Phi"                 value="0"               type="double" />
            <attdef   name="Theta"               desc="" category="Draw" extra="" />
            <attvalue name="Theta"               value="0"               type="double" />
            <attdef   name="Omega"               desc="" category="Draw" extra="" />
            <attvalue name="Omega"               value="0"               type="double" />
            <attdef   name="Radius1"             desc="" category="Draw" extra="" />
            <attvalue name="Radius1"             value="5"               type="double" />
            <attdef   name="Radius2"             desc="" category="Draw" extra="" />
            <attvalue name="Radius2"             value="5"               type="double" />
            <attdef   name="Radius3"             desc="" category="Draw" extra="" />
            <attvalue name="Radius3"             value="5"               type="double" />
            <attdef   name="Curvature"           desc="" category="Draw" extra="" />
            <attvalue name="Curvature"           value="0.2"             type="double" />
            <attdef   name="FlyLength"           desc="" category="Draw" extra="" />
            <attvalue name="FlyLength"           value="10"              type="double" />
            <attdef   name="Faces"               desc="" category="Draw" extra="" />
            <attvalue name="Faces"               value="4"               type="int" />

        <!-- 2D TextAtts -->
            <attdef   name="Text"                desc="" category="Draw" extra="" />
            <attvalue name="Text"                value=""                type="String" />
            <attdef   name="HPos"                desc="" category="Draw" extra="" />
            <attvalue name="HPos"                value="0.0"             type="double" />
            <attdef   name="VPos"                desc="" category="Draw" extra="" />
            <attvalue name="VPos"                value="0.5"             type="double" />
            <attdef   name="HAlign"              desc="" category="Draw" extra="" />
            <attvalue name="HAlign"              value="Left"            type="String" />
            <attdef   name="VAlign"              desc="" category="Draw" extra="" />
            <attvalue name="VAlign"              value="Baseline"        type="String" />

        <!-- PickAtts -->
            <attdef   name="IsPickable"             desc="" category="PickAction" extra="" />
            <attvalue name="IsPickable"             value="true"                  type="boolean" />
            <attdef   name="ShowParentAttributes"   desc="" category="PickAction" extra="" />
            <attvalue name="ShowParentAttributes"   value="false"                 type="boolean" />
            <attdef   name="PickParent"             desc="" category="PickAction" extra="" />
            <attvalue name="PickParent"             value="false"                 type="boolean" />
            
        </type>
    </typetree>
</heprep>

=== kdk-pkg-soft/freehep-ncolor-pdf/heprep/freehep-jheprep1/src/main/java/hep/graphics/heprep1/xml/test/PolyPoint.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<heprep:heprep xmlns:heprep='http://java.freehep.org/schemas/heprep/1.0'
               xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance' 
               xsi:schemaLocation='http://java.freehep.org/schemas/heprep/1.0 http://java.freehep.org/schemas/heprep/1.0/HepRep.xsd'>

    <heprep:type name="TestPolyPoint">
        <heprep:attvalue name="drawAs" value="PolyPoint" />
        <heprep:instance>
            <heprep:primitive>
                <heprep:point x="0.0" y="0.0" z="0.0" />
                <heprep:point x="1.0" y="1.0" z="1.0" />
                <heprep:point x="2.0" y="2.0" z="2.0" />
                <heprep:point x="3.0" y="3.0" z="3.0" />
                <heprep:point x="4.0" y="4.0" z="4.0" />
            </heprep:primitive>
            <heprep:primitive>
                <heprep:attvalue name="MarkName" value="Triangle"/>
                <heprep:point x="10.0" y="10.0" z="10.0" />
                <heprep:point x="11.0" y="11.0" z="11.0" />
                <heprep:point x="12.0" y="12.0" z="12.0" />
                <heprep:point x="13.0" y="13.0" z="13.0" />
                <heprep:point x="14.0" y="14.0" z="14.0" />
            </heprep:primitive>            
            <heprep:primitive>
                <heprep:attvalue name="MarkSize" value="5"/>
                <heprep:point x="-10.0" y="10.0" z="10.0" />
                <heprep:point x="-20.0" y="20.0" z="20.0" />
                <heprep:point x="-30.0" y="30.0" z="30.0" />
                <heprep:point x="-40.0" y="40.0" z="40.0" />
                <heprep:point x="-50.0" y="50.0" z="50.0" />
            </heprep:primitive>            
        </heprep:instance>        
    </heprep:type>

</heprep:heprep>
